# <a href = "../README.md" target="_blank">스프링 DB 1편 - 데이터 접근 핵심 원리</a>
## Chapter 06. 스프링과 문제 해결 - 예외 처리, 반복
### 6.2 런타임 예외 적용
1) (실습) 런타임 예외 MyDbExecption 정의
2) (실습) 체크예외 전환, 인터페이스 구현 : MemberRepositoryV4_1
3) 예외 전환 시 원인이 되는 예외를 내부에 포함해야한다. (다시 강조)
4) (실습) 인터페이스 의존 서비스 : MemberServiceV4
5) (실습) 테스트 코드 적용 : MemberServiceV4Test
6) 결론 : 인터페이스 및 서비스 계층의 특정 기술 종속성 완벽 제거
7) 남은 문제 : 감싼 체크예외가 무엇인지 구분할 수 없음

---

# 6.2 런타임 예외 적용

---

## 1) (실습) 런타임 예외 MyDbExecption 정의
```java
public class MyDbException extends RuntimeException {

    public MyDbException() {
    }

    public MyDbException(String message) {
        super(message);
    }

    public MyDbException(String message, Throwable cause) {
        super(message, cause);
    }

    public MyDbException(Throwable cause) {
        super(cause);
    }
}

```
- 체크예외를 런타임예외로 전환해야하는데, 따로 전환할 런타임 예외를 정의한다.

---

## 2) (실습) 체크예외 전환, 인터페이스 구현 : MemberRepositoryV4_1
```java

@Slf4j
public class MemberRepositoryV4_1 implements MemberRepository { // 인터페이스 구현
    
    // 생략
    
    @Override
    public Member save(Member member) { // throws 사라짐
        
        // 생략
        try {
            
            // 생략

        } catch (SQLException e) {
            throw new MyDbException(e); // 체크예외인 SQLException을 런타임 예외로 전환
        } finally {
            close(conn, pstmt, null);
        }
    }
}
```
- MemberRepository 인터페이스를 구현한다.
- 이 코드에서 핵심은 `SQLException` 이라는 체크 예외를 MyDbException 이라는 런타임 예외로 변환해서 던지는 부분이다.

---

## 3) 예외 전환 시 원인이 되는 예외를 내부에 포함해야한다. (다시 강조)

### 3.1 원인 예외 포함
```java
    } catch (SQLException e) {
                throw new MyDbException(e); // 체크예외인 SQLException을 런타임 예외로 전환
    }
```
- 예외는 원인이 되는 예외를 내부에 포함할 수 있는데, 꼭 이렇게 작성해야 한다.
- 그래야 예외를 출력했을 때 원인이 되는 기존 예외도 함께 확인할 수 있다.
- `MyDbException` 이 내부에 `SQLException` 을 포함하고 있다고 이해하면 된다
- 예외를 출력했을 때 스택 트레이스를 통해 둘다 확인할 수 있다.

### 3.2 원인 예외를 미포함했을 때
```java
} catch (SQLException e) {
    throw new MyDbException();
}
```
- 잘 보면 `new MyDbException()` 으로 해당 예외만 생성하고 기존에 있는 SQLException 은 포함하지 않고 무시한다.
- 따라서 `MyDbException` 은 내부에 원인이 되는 다른 예외를 포함하지 않는다.
- 이렇게 원인이 되는 예외를 내부에 포함하지 않으면, 예외를 스택 트레이스를 통해 출력했을 때 기존에 원인이 되는 부분을 확인할 수 없다.
  - 만약 SQLException 에서 문법 오류가 발생했다면 그 부분을 확인할 방법이 없게 된다.

### 3.3 결론 : 원인 예외를 꼭 포함 시켜라
- 예외를 변환할 때는 기존 예외를 꼭! 포함하자.
- 장애가 발생하고 로그에서 진짜 원인이 남지 않는 심각한 문제가 발생할 수 있다. 중요한 내용이어서 한번 더 설명됨

---

## 4) (실습) 인터페이스 의존 서비스 : MemberServiceV4
```java
@Slf4j
@RequiredArgsConstructor
public class MemberServiceV4 {

    private final MemberRepository memberRepository; // 인터페이스 의존
    
    @Transactional
    public void accountTransfer(String fromId, String toId, int money) { // 더 이상 throws 예외를 하지 않아도 됨
        businessLogic(fromId, toId, money);
    }

    private void businessLogic(String fromId, String toId, int money) {
        // 비즈니스 로직 수행
        Member fromMember = memberRepository.findById(fromId);
        Member toMember = memberRepository.findById(toId);

        memberRepository.update(fromId, fromMember.getMoney() - money);

        validation(toMember);

        memberRepository.update(toId, toMember.getMoney() + money);
    }
}
```
- `MemberRepository` 인터페이스에 의존하도록 코드를 변경했다.
- `MemberServiceV3_3` 와 비교해서 보면 드디어 메서드에서 throws SQLException 부분이 제거된 것을 확인할 수 있다.
- 드디어 순수한 서비스를 완성했다.

---

## 5) (실습) 테스트 코드 적용 : MemberServiceV4Test
```java
@Slf4j
@SpringBootTest
class MemberServiceV4Test {

    @Autowired
    private MemberRepository memberRepository;
    @Autowired
    private MemberServiceV4 memberService;

    @TestConfiguration
    @RequiredArgsConstructor
    static class TestConfig {

        private final DataSource dataSource;

        @Bean
        MemberRepository memberRepository() {
            return new MemberRepositoryV4_1(dataSource);
        }

        @Bean
        MemberServiceV4 memberServiceV4() {
            return new MemberServiceV4(memberRepository());
        }
    }
}
```
- `MemberRepository` 인터페이스를 사용하도록 했다.
- 테스트가 모두 정상 동작하는 것을 확인할 수 있다.

---

## 6) 결론 : 인터페이스 및 서비스 계층의 특정 기술 종속성 완벽 제거
- 체크 예외를 런타임 예외로 변환하면서 인터페이스와 서비스 계층의 순수성을 유지할 수 있게 되었다.
- 덕분에 향후 JDBC에서 다른 구현 기술로 변경하더라도 서비스 계층의 코드를 변경하지 않고 유지할 수 있다.

---

## 7) 남은 문제 : 감싼 체크예외가 무엇인지 구분할 수 없음
- 리포지토리에서 넘어오는 특정한 예외의 경우 복구를 시도할 수도 있다.
- 그런데 지금 방식은 항상 `MyDbException` 이라는 예외만 넘어오기 때문에 예외를 구분할 수 없는 단점이 있다.
- 만약 특정 상황에는 예외를 잡아서 복구하고 싶으면 예외를 어떻게 구분해서 처리할 수 있을까?

---
